name: Continuous Integration

on:
  push:
    branches: [master, develop]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  all:
    name: Tests & Check (Code + Rust Formatting)
    strategy:
      matrix:
        rust: ["stable"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust Toolchain(s)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: 'x86_64-unknown-linux-gnu'
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo test (release)
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "-D warnings"
        with:
          command: test
          args: --release --target x86_64-unknown-linux-gnu

      - name: Cargo check (release)
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "-D warnings"
        with:
          command: check
          args: --release

      - name: Check formating
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "-D warnings"
        with:
          command: fmt
          args: --all -- --check